"""Stage 5 — AI refactor of raw_recording.py into selectors.yaml + navigate steps."""

from __future__ import annotations

import argparse
import json
import py_compile
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).parent))
from lib.llm_call import ask


PROMPT_TEMPLATE = """You are refactoring Playwright codegen output into a maintainable structure.

The generated ``navigate.py`` is APPENDED to a template that already provides
the following module-level helpers — DO NOT redefine any of them:
  - ``find(page, name, timeout_ms)`` → Locator (handles selector fallback chain + AI healing)
  - ``selectors()``, ``load_selectors()``, ``save_selectors()``
  - ``log`` (module logger named for this project)
  - ``Page``, ``Locator`` from playwright.sync_api are imported
The template also provides an ``execute_download(page, config)`` adapter that
calls your generated ``steps()`` and saves the result. You write ONLY ``steps``.

Split the following raw recording into three outputs:

1. selectors_yaml — each interaction point as a YAML entry with:
   - description (Korean, human readable)
   - primary (robust selector from recording: prefer data-test, aria-label, id)
   - fallbacks (2-4 alternatives using text=, xpath=, role=)
   - ai_discovered: [] (empty initially)

2. navigate_py — Python code defining a single function ``steps(page, config) -> dict``.
   - Use ``find(page, "<name>")`` calls instead of raw page.locator/click.
   - Wrap each logical step with a ``log.info()`` call.
   - For the file download, use Playwright's ``with page.expect_download() as dl_info:``
     pattern, then **save the file to disk** by calling
     ``download.save_as(str(save_path))`` where ``save_path`` is built from
     ``download.resolve_save_dir(config)`` (import locally from ``download``).
     Return a dict containing ``"download_path": save_path``. The template's
     ``execute_download`` adapter unwraps this to the file path that run.py
     hands off to validators.
   - DO NOT redefine ``find``, ``selectors``, ``log``, or import Page/Locator
     again — they exist at module scope already.

3. config_patches — any hardcoded dates/values turned into template variables
   (supported: {today}, {today-Nd}, {yesterday}, {this_month_start}).
   Return as a dict of dotted-path -> new value.

Raw recording:
<RECORDING>

Project context:
  URL: <URL>
  Expected columns: <COLS>

Respond with JSON ONLY in this exact shape:
{
  "selectors_yaml": "<yaml string>",
  "navigate_py": "<python code string>",
  "config_patches": { "path.to.key": "new_value" }
}
"""


def build_prompt(recording: str, config: dict) -> str:
    url = config.get("project", {}).get("url", "?")
    cols = config.get("validation", {}).get("expected_columns", [])
    return (PROMPT_TEMPLATE
            .replace("<RECORDING>", recording)
            .replace("<URL>", url)
            .replace("<COLS>", ", ".join(cols) if cols else "(none specified)"))


def merge_yaml(existing_path: Path, new_yaml_str: str) -> None:
    existing = {}
    if existing_path.exists():
        try:
            existing = yaml.safe_load(existing_path.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            existing = {}
    new = yaml.safe_load(new_yaml_str) or {}
    existing.update(new)
    with existing_path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(existing, f, allow_unicode=True, sort_keys=False)


def apply_refactor_result(project_dir: Path, result: dict) -> None:
    # selectors.yaml (merge with existing)
    merge_yaml(project_dir / "selectors.yaml", result["selectors_yaml"])

    # navigate.py — append the steps() function
    nav_path = project_dir / "src" / "navigate.py"
    existing = nav_path.read_text(encoding="utf-8") if nav_path.exists() else ""
    if "def steps(" not in existing:
        # Append after the final newline
        separator = "\n\n# --- Generated by refactor (Stage 5) ---\n"
        nav_path.parent.mkdir(parents=True, exist_ok=True)
        nav_path.write_text(existing + separator + result["navigate_py"].strip() + "\n",
                            encoding="utf-8")

    # config patches
    cfg_path = project_dir / "config.yaml"
    if cfg_path.exists() and result.get("config_patches"):
        cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8")) or {}
        for dotted, value in result["config_patches"].items():
            parts = dotted.split(".")
            node = cfg
            for p in parts[:-1]:
                node = node.setdefault(p, {})
            node[parts[-1]] = value
        with cfg_path.open("w", encoding="utf-8") as f:
            yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False)


def verify_syntax(project_dir: Path) -> tuple[bool, str]:
    nav_path = project_dir / "src" / "navigate.py"
    if not nav_path.exists():
        return False, f"{nav_path} missing"
    try:
        py_compile.compile(str(nav_path), doraise=True)
        return True, ""
    except py_compile.PyCompileError as e:
        return False, str(e)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("project_dir", type=Path)
    parser.add_argument("--dry-run", action="store_true",
                        help="Print prompt + mock result without LLM call")
    parser.add_argument(
        "--model",
        default=None,
        help="Override the LLM model (e.g. 'claude-haiku-4-5' to dodge "
        "sonnet rate limits). Default: provider's recommended model.",
    )
    args = parser.parse_args()

    project_dir = args.project_dir.resolve()
    rec_path = project_dir / "recordings" / "raw_recording.py"
    if not rec_path.exists():
        print(f"Recording not found: {rec_path}. Run Stage 4 (record_flow.py) first.", file=sys.stderr)
        return 5
    cfg_path = project_dir / "config.yaml"
    if not cfg_path.exists():
        print(f"Config not found: {cfg_path}. Run Stage 1 (scope.py) first.", file=sys.stderr)
        return 5
    recording = rec_path.read_text(encoding="utf-8")
    config = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    model_hint = args.model or (config.get("healing") or {}).get("ai_model") or None

    prompt = build_prompt(recording, config)
    if args.dry_run:
        print(prompt)
        return 0

    try:
        result = ask(prompt, preference=config["healing"]["ai_provider"],
                     model_hint=model_hint, max_tokens=4000)
    except Exception as e:
        print(f"LLM call failed: {e}", file=sys.stderr)
        return 2

    for key in ("selectors_yaml", "navigate_py"):
        if key not in result:
            print(f"LLM response missing key: {key}", file=sys.stderr)
            print(json.dumps(result, ensure_ascii=False)[:500], file=sys.stderr)
            return 3

    apply_refactor_result(project_dir, result)
    ok, err = verify_syntax(project_dir)
    if not ok:
        print(f"Syntax check failed: {err}", file=sys.stderr)
        # Retry once with error message in prompt
        retry_prompt = prompt + f"\n\nPrevious attempt had syntax error:\n{err}\nFix it."
        result2 = ask(retry_prompt, preference=config["healing"]["ai_provider"],
                      model_hint=model_hint, max_tokens=4000)
        apply_refactor_result(project_dir, result2)
        ok, err = verify_syntax(project_dir)
        if not ok:
            print(f"Retry also failed: {err}", file=sys.stderr)
            return 4

    print(f"Refactored: selectors.yaml + src/navigate.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
